# Generated by Django 5.0.4 on 2024-05-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review_review_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='db_review',
        ),
        migrations.AlterModelTable(
            name='streamplatform',
            table='db_streamplatform',
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='db_watchlist',
        ),
    ]
